apiVersion: v1
kind: ConfigMap
metadata:
  name: agent-config
data:
  JAVA_TOOL_OPTIONS: -javaagent:/agent/opentelemetry-javaagent-all.jar
  OTEL_TRACES_EXPORTER: otlp
  OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector.istio-system:4317
  OTEL_METRICS_EXPORTER: none
  OTEL_PROPAGATORS: b3multi
  OTEL_JAVAAGENT_DEBUG: "true"
