{
 "title": "Performance Test",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "tsService",
    "label": "TrainTicket Services",
    "query": {
     "query": "container_cpu_usage_seconds_total{container!=\"POD\"}"
    }
   },
   {
    "name": "copy_of_tsService",
    "label": "TrainTicket Services",
    "query": {
     "query": "container_cpu_usage_seconds_total{container!=\"POD\",name=~\"(k8s_ts-).+\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster CPU Utilization",
   "type": "graph",
   "description": "How many cores are currently used up across the entire cluster.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{id=\"/\"}[2m]))"
    }
   ]
  },
  {
   "title": "Current Cluster CPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{id=\"/\"}[2m]))/sum(machine_cpu_cores)"
    }
   ]
  },
  { "title": "${tsService}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }, "repeat": "tsService" },
  {
   "title": "Container CPU Load",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "yaxes": [
    { "format": "cores", "label": "CPU utilization" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"${tsService}\"}[2m]))"
    }
   ]
  },
  {
   "title": "Average Container CPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"${tsService}\"}[2m]))",
     "legendFormat": "Average CPU Utilization"
    }
   ]
  },
  {
   "title": "Average Container CPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"${tsService}\"}[1m]))/sum(container_spec_cpu_quota{container=\"${tsService}\"}/container_spec_cpu_period{container=\"${tsService}\"})"
    }
   ]
  },
  {
   "title": "Max CPU",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 20, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"${tsService}\"}[2m]))"
    }
   ]
  },
  {
   "title": "Min CPU",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 20, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"${tsService}\"}[2m]))"
    }
   ]
  },
  {
   "title": "Max Memory",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 20, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_memory_usage_bytes{container=\"${tsService}\"}[2m]))"
    }
   ]
  },
  {
   "title": "Container Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes", "label": "Memory usage" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_memory_usage_bytes{container=\"${tsService}\"}[2m]))"
    }
   ]
  },
  {
   "title": "Average Memory Consumption",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_memory_usage_bytes{container=\"${tsService}\"}[2m]))"
    }
   ]
  },
  {
   "title": "Min Memory",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 20, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_memory_usage_bytes{container=\"${tsService}\"}[2m]))"
    }
   ]
  },
  {
   "title": "Max Bytes Sent",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 20, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{pod=~\"${tsService}.*\"}[2m]))"
    }
   ]
  },
  {
   "title": "Container network traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes sent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{pod=~\"${tsService}.*\"}[2m]))",
     "legendFormat": "Transmitted bytes"
    },
    {
     "expr": "sum(rate(container_network_transmit_packets_total{pod=~\"${tsService}.*\"}[2m]))",
     "legendFormat": "Transmitted packets"
    }
   ]
  },
  {
   "title": "Average Bytes sent",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{pod=~\"${tsService}.*\"}[2m]))"
    }
   ]
  },
  {
   "title": "Min Bytes Sent",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 20, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{pod=~\"${tsService}.*\"}[2m]))"
    }
   ]
  },
  { "title": "${tsService}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Container CPU Load",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "yaxes": [
    { "format": "cores", "label": "CPU utilization" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"${tsService}\"}[2m]))"
    }
   ]
  },
  {
   "title": "Average Container CPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"${tsService}\"}[2m]))",
     "legendFormat": "Average CPU Utilization"
    }
   ]
  },
  {
   "title": "Average Container CPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 16, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"${tsService}\"}[1m]))/sum(container_spec_cpu_quota{container=\"${tsService}\"}/container_spec_cpu_period{container=\"${tsService}\"})"
    }
   ]
  },
  {
   "title": "Max CPU",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 20, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"${tsService}\"}[2m]))"
    }
   ]
  },
  {
   "title": "Min CPU",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 20, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"${tsService}\"}[2m]))"
    }
   ]
  },
  {
   "title": "Max Memory",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 20, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_memory_usage_bytes{container=\"${tsService}\"}[2m]))"
    }
   ]
  },
  {
   "title": "Container Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes", "label": "Memory usage" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_memory_usage_bytes{container=\"${tsService}\"}[2m]))"
    }
   ]
  },
  {
   "title": "Average Memory Consumption",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_memory_usage_bytes{container=\"${tsService}\"}[2m]))"
    }
   ]
  },
  {
   "title": "Min Memory",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 20, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_memory_usage_bytes{container=\"${tsService}\"}[2m]))"
    }
   ]
  },
  {
   "title": "Max Bytes Sent",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 20, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{pod=~\"${tsService}.*\"}[2m]))"
    }
   ]
  },
  {
   "title": "Container network traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes sent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{pod=~\"${tsService}.*\"}[2m]))",
     "legendFormat": "Transmitted bytes"
    },
    {
     "expr": "sum(rate(container_network_transmit_packets_total{pod=~\"${tsService}.*\"}[2m]))",
     "legendFormat": "Transmitted packets"
    }
   ]
  },
  {
   "title": "Average Bytes sent",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{pod=~\"${tsService}.*\"}[2m]))"
    }
   ]
  },
  {
   "title": "Min Bytes Sent",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 20, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{pod=~\"${tsService}.*\"}[2m]))"
    }
   ]
  }
 ]
}